"""Initial migration

Revision ID: a46925cd8965
Revises: 
Create Date: 2025-07-02 10:44:28.170433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a46925cd8965'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_karchag_texts_id'), table_name='karchag_texts')
    op.drop_table('karchag_texts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('karchag_texts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sub_category_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('derge_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('yeshe_de_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tibetan_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chinese_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sanskrit_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('english_title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sermon_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yana_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('translation_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], name=op.f('karchag_texts_sermon_id_fkey')),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], name=op.f('karchag_texts_sub_category_id_fkey')),
    sa.ForeignKeyConstraint(['translation_type_id'], ['translation_types.id'], name=op.f('karchag_texts_translation_type_id_fkey')),
    sa.ForeignKeyConstraint(['yana_id'], ['yanas.id'], name=op.f('karchag_texts_yana_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('karchag_texts_pkey'))
    )
    op.create_index(op.f('ix_karchag_texts_id'), 'karchag_texts', ['id'], unique=False)
    # ### end Alembic commands ###
